[package]
name = "eoclient"
version = "0.1.0"
authors = ["Richard Leek <richard@richardleek.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfml = "0.16.0"
pelite = "0.9.0"
byteorder = "1"